apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
      name: webserver
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
        - name: "443"
          port: 443
          targetPort: 443
      selector:
        io.kompose.service: webserver
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: app
      name: app
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: app
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o deployment.yml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.network/app-network: "true"
            io.kompose.service: app
        spec:
          containers:
            - env:
                - name: SERVICE_NAME
                  value: app
                - name: SERVICE_TAGS
                  value: dev
              image: digitalocean.com/php
              name: laravelapp-app
              resources: {}
              tty: true
              volumeMounts:
                - mountPath: /var/www
                  name: app-claim0
                - mountPath: /usr/local/etc/php/conf.d/local.ini
                  name: app-claim1
              workingDir: /var/www
          restartPolicy: Always
          volumes:
            - name: app-claim0
              persistentVolumeClaim:
                claimName: app-claim0
            - name: app-claim1
              persistentVolumeClaim:
                claimName: app-claim1
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app-claim0
      name: app-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app-claim1
      name: app-claim1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: app-network
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/app-network: "true"
      podSelector:
        matchLabels:
          io.kompose.network/app-network: "true"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o deployment.yml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.network/app-network: "true"
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  value: 6valy_db
                - name: MYSQL_ROOT_HOST
                  value: '%'
                - name: MYSQL_ROOT_PASSWORD
                  value: root
                - name: MYSQL_USER
                  value: admin
                - name: SERVICE_NAME
                  value: mysql
                - name: SERVICE_TAGS
                  value: dev
              image: mysql:5.7
              name: laravelapp-db
              ports:
                - containerPort: 3306
              resources: {}
              tty: true
              volumeMounts:
                - mountPath: /etc/mysql/my.cnf
                  name: db-claim0
                - mountPath: /var/lib/mysql/
                  name: dbdata
          restartPolicy: Always
          volumes:
            - name: db-claim0
              persistentVolumeClaim:
                claimName: db-claim0
            - name: dbdata
              persistentVolumeClaim:
                claimName: dbdata
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-claim0
      name: db-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dbdata
      name: dbdata
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
      name: webserver
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: webserver
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o deployment.yml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.network/app-network: "true"
            io.kompose.service: webserver
        spec:
          containers:
            - image: nginx:alpine
              name: laravelapp-webserver
              ports:
                - containerPort: 80
                - containerPort: 443
              resources: {}
              tty: true
              volumeMounts:
                - mountPath: /var/www
                  name: webserver-claim0
                - mountPath: /etc/nginx/conf.d/
                  name: webserver-claim1
          restartPolicy: Always
          volumes:
            - name: webserver-claim0
              persistentVolumeClaim:
                claimName: webserver-claim0
            - name: webserver-claim1
              persistentVolumeClaim:
                claimName: webserver-claim1
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver-claim0
      name: webserver-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver-claim1
      name: webserver-claim1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

